### ISSUE TITLE
New Landing Page

### ISSUE THREAD

**Issue by pjnovas** [danzajdband/hackdash#100]
- [x] Create Dashboard
- [x] Search Dashboard
- [x] Search Projects
- [x] Search Collections
- [x] Search Users
- [ ] ~~Feed~~ moved to #116 
- [x] Counters
- [x] Team
- [ ] Partners

**Comment by danzajdband** [comment]
It will be nice to merge this with `/live` under `/feed`.

Thoughts?

**Comment by pjnovas** [comment]
Wrapping up list:

- [ ] Collection create and edit
- [ ] Dashboard page: Footer buttons style
- [ ] Project page: buttons style and github import for create
- [ ] Profile page: list items style
- [ ] Dashboard card: picture
- [ ] Project card: command bar
- [ ] Landing: team styles and partners
