### ISSUE TITLE
MetaData for Facebook/Linkedin/Twitter

### ISSUE THREAD

**Issue by marianet** [danzajdband/hackdash#112]
When you post a link http://hackslabs.hackdash.org/ Metadata description should need to showup. Title, Description of the dashboard, first picture of the dashboard
also in the project http://hackslabs.hackdash.org/projects/540239591c1f227a76000097

**Comment by pjnovas** [comment]
- [ ] meta data for twitter

**Comment by pjnovas** [comment]
- [ ] if dashboard has no description, use first project description for metas
