### ISSUE TITLE
Some HackDash instances referenced on README.md is not working.

### ISSUE THREAD

**Issue by jkutianski** [danzajdband/hackdash#119]
[README.md](https://github.com/danzajdband/hackdash/blob/master/README.md)
Auth0 HackDash returns "500 MongoError"
BAHackaton returns "No such app"

**Comment by pjnovas** [comment]
@danzajdband any thoughts about this?

**Comment by danzajdband** [comment]
We can remove that section from the Readme and move it to the wiki (only
the working projects :p)

**Comment by jkutianski** [comment]
Hey @danzajdband! I found this instance http://urbantext.org/, but looks unused.

**Comment by jkutianski** [comment]
Also found this http://bahackatonverde.herokuapp.com/ but looks to be unmanaged for a long time.

**Comment by danzajdband** [comment]
We can add those too. Both are nice examples.
