### ISSUE TITLE
[Dokku/Heroku] less-middleware is in devDependencies, but needed by server.js

### ISSUE THREAD

**Issue by almereyda** [danzajdband/hackdash#120]
I am running Hackdash on Dokku.

For running Hackdash, I have to manually [enable the installation of devDependencies](https://github.com/heroku/heroku-buildpack-nodejs#enable-or-disable-devdependencies-installation) for the nodejs-buildpack.

Thus installation may also fail for Heroku with the old installation instructions in the blog post.

Thanks for the new design, though.

**Comment by pjnovas** [comment]
@almereyda that's right!, just moved, thanks for the heads up.
