### ISSUE TITLE
Where to get User _ids for Team?

### ISSUE THREAD

**Issue by almereyda** [danzajdband/hackdash#121]
The readme talks about IDs, but I don't know where to get them from.
Any hints?

**Comment by pjnovas** [comment]
@almereyda those are the ids from users collection on your mongo database. You can get them from the URL by entering a profile like: `[your-domain]/users/[_id]` or by querying your database.

**Comment by almereyda** [comment]
This is tough. My Mongo is running in a linked container on a PaaS (Dokku).

For showing a profile as you proposed, I would know the _id beforehand, so
this doesn't work, too.
Are there no simpler ways?

**Comment by pjnovas** [comment]
That section is meant to set profile's (which are already inside the database) as the team for the site.
You can add those ids beforehand and if I'm not wrong, it wont break, if is not found wont do anything.

What you can do is hide Team section from html, I didn't think about not showing Team section, so it could be better to not show Team section when the ids array is empty, I'm gonna add it as a feature.

Thanks.

**Comment by almereyda** [comment]
Well, I'd rather have a way to get the `_id`, like in a user's profile when
I am site admin ;)
