### ISSUE TITLE
Provide API

### ISSUE THREAD

**Issue by DavidLemayian** [danzajdband/hackdash#69]
It would be great to have an API that could work with tools like [Dug.js](http://rog.ie/blog/dugjs-a-jsonp-to-html-script).

**Comment by kyyberi** [comment]
Another option instead of JSONP is to provide JSON and use CORS headers. http://enable-cors.org/

**Comment by jkutianski** [comment]
+1 to JSON + CORS

**Comment by danzajdband** [comment]
+1

**Comment by danzajdband** [comment]
I'll add CORS for some GET methods and keep you posted.

**Comment by danzajdband** [comment]
@pjnovas is this already on production?

**Comment by pjnovas** [comment]
@danzajdband I'm testing it at stagging, will be this afternoon with docs :)

**Comment by danzajdband** [comment]
Awesome

**Comment by pjnovas** [comment]
@danzajdband oh now I got it, it gets auto-closed from your commit message haha.
I'm come back as soon as it is ready.

**Comment by danzajdband** [comment]
:P

**Comment by pjnovas** [comment]
This is ready, docs updated [here](https://github.com/danzajdband/hackdash/wiki/RESTfull-API)
Separated CORS support at https://github.com/danzajdband/hackdash/wiki/RESTfull-API#cross-origin-resource-sharing-cors

Enjoy!

**Comment by DavidLemayian** [comment]
Excellent! Thank you guys.

**Comment by danzajdband** [comment]
@DavidLemayian Let us know if you implement something ;)
