### ISSUE TITLE
Link on the logo is confusing

### ISSUE THREAD

**Issue by rusosnith** [danzajdband/hackdash#89]
Clicking on the logo of Hackdash takes people away from the sub.hackdash where they are, this is confusing for most of people.

I propose clicking on the hackdash logo AND on the sub.hackdash title, get's to the home of the sub.hackdash

Another link, probably at the bottom, should go to the main root hackdash page.

In the dbootcamp UY, lot's of people got confused and made new sub.hackdash pages instead of new projects inside dbootcamp.hackdash

**Comment by kyyberi** [comment]
Still "feature" is really annoying

**Comment by pjnovas** [comment]
This has been splited into a different approach with the new front-end. 
Hope it is more clear now. If it's still annoying we can re-think it.
