### ISSUE TITLE
"Log in" wordin on the homepage is missleading for contribuitors

### ISSUE THREAD

**Issue by wolfmat** [danzajdband/hackdash#93]
In an instance like the one running http://larutauy.hackdash.org/ right now, the big *log in* on the home page is missleading for potential contributors. The button says:

*Log in to create a project*

When actually if you just want to join to an existing project as a contribuitor, you have to do exactly that - log in through the same button, and then you get to *join* to it.

Perhaps it should say something like "Log in to create or join a project".

**Comment by pjnovas** [comment]
The login approach has been changed now. 
Feel free to reopen if still has issues. Thanks!
