### ISSUE TITLE
Replace subdomains with /:dashboard_name

### ISSUE THREAD

**Issue by danzajdband** [danzajdband/hackdash#97]
Moving from subdomains to subroutes will improve the development flow and make the use of SSL certificate simple.

**Comment by pjnovas** [comment]
Created a Wiki to follow the current website urls and new proposals for removing subdomains.
https://github.com/danzajdband/hackdash/wiki/WebSite-URLs

**Comment by pjnovas** [comment]
This is a note for me:
At new landing page, the dashboard name entered as "domain" is going to be the first title + the perma-link (separating spaces with -). Which will have a better max of chars (check later which would be better)

**Comment by pjnovas** [comment]
moved dashboards to url, kept subdomains as a redirect for now.

**Comment by danzajdband** [comment]
boom!
